apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  keystone:
    template:
      databaseInstance: openstack
      secret: osp-secret
  mariadb:
    enabled: false
    templates:
      openstack:
        storageRequest: 500M
      openstack-cell1:
        storageRequest: 500M
  galera:
    enabled: true
    templates:
      openstack:
        storageClass: local-storage
        storageRequest: 500M
        secret: osp-secret
        replicas: 3
      openstack-cell1:
        storageClass: local-storage
        storageRequest: 500M
        secret: osp-secret
        replicas: 3
  rabbitmq:
    templates:
      rabbitmq:
        replicas: 1
        #resources:
        #  requests:
        #    cpu: 500m
        #    memory: 1Gi
        #  limits:
        #    cpu: 800m
        #    memory: 1Gi
      rabbitmq-cell1:
        replicas: 1
  memcached:
    enabled: true
  placement:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-placement-api:current-tripleo
      secret: osp-secret
  glance:
    template:
      databaseInstance: openstack
      storageClass: ""
      storageRequest: 10G
  cinder:
    template:
      databaseInstance: openstack
      secret: osp-secret
      cinderAPI:
        replicas: 1
      cinderScheduler:
        replicas: 1
      cinderBackup:
        replicas: 0 # backend needs to be configured
      cinderVolumes:
        volume1:
          replicas: 0 # backend needs to be configured
  manila:
    template:
      manilaAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-api:current-tripleo
      manilaScheduler:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-scheduler:current-tripleo
      manilaShares:
        share1:
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
  ovn:
    template:
      ovnDBCluster:
        ovndbcluster-nb:
          replicas: 1
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-nb-db-server:current-tripleo
          dbType: NB
          storageRequest: 10G
        ovndbcluster-sb:
          replicas: 1
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-sb-db-server:current-tripleo
          dbType: SB
          storageRequest: 10G
      ovnNorthd:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ovn-northd:current-tripleo
  ovs:
    template:
      ovsContainerImage: "quay.io/skaplons/ovs:latest"
      ovnContainerImage: "quay.io/tripleozedcentos9/openstack-ovn-controller:current-tripleo"
      external-ids:
        system-id: "random"
        ovn-bridge: "br-int"
        ovn-encap-type: "geneve"
  neutron:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-neutron-server:current-tripleo
      secret: osp-secret
  horizon:
    template:
      replicas: 1
      secret: osp-secret
  nova:
    template:
      secret: osp-secret
  ironic:
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-api:current-tripleo
      ironicConductors:
      - replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
        storageRequest: 10G
        storageClass: local-storage
      ironicInspector:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-inspector:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
      secret: osp-secret
